name: 'Download'
on: workflow_dispatch
jobs:

  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: upload.yml
          commit: ${{ github.sha }}
          name: test_${{ github.sha }}

      - name: Display structure of downloaded files
        run: ls -R
